empleado/applications/departamento/urls.py
"""
"""

from django.urls import path
from . import views

app_name = 'departamento_app'
urlpatterns = [
    path('listar_departamentos/', views.DepartamentoListView.as_view(),
         name='lista_departamento'),
    path('new-departamento/',views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

empleado/applications/personal/urls.py
"""
"""
from django.urls import path
from . import views

app_name = 'personal_app'
urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_by_areas/<shorname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('listar_empleados/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('listar_by_kword/', views.ListEmpleadosByKword.as_view()),
    path('listar_by_habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar'),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la app departamento
    #path('depart/', include('applications.departamento.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Empleado</li>
            <li>
                <a href="{% url 'personal_app:empleados_all' %}">Listar</a>
            </li>
            <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamento</a></li>
            <li><a href="{% url 'personal_app:empleados_admin' %}">Administrar</a></li>
            <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
        </ul>
    </div>
    <div class="grid-x top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Search"></li>
            <li><button type="button" class="button">Buscar Empleado</button></li>
        </ul>
        <ul>
            <br>
        </ul>
        <ul class="menu">
            <li><a href="{% url 'personal_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
        </ul>
    </div>
</div>