empleado/applications/departamento/urls.py
"""
"""

from django.urls import path
from . import views

app_name = 'departamento_app'
urlpatterns = [
    path('listar_departamentos/', views.DepartamentoListView.as_view(),
         name='lista_departamento'),
    path('new-departamento/',views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

empleado/applications/personal/urls.py
"""
"""
from django.urls import path
from . import views

app_name = 'personal_app'
urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_by_areas/<shorname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('listar_empleados/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('listar_by_kword/', views.ListEmpleadosByKword.as_view()),
    path('listar_by_habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar'),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la app departamento
    #path('depart/', include('applications.departamento.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre',max_length=50)
    shor_name = models.CharField('NombreCorto',max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    # Defino algunas caracteristicas para el admin. de Django
    class Meta:
      verbose_name = 'Department' # Nombre de Columna singular
      verbose_name_plural = 'My Departments' # Nombre en plural
      ordering = ['id'] # Ordenar como se ver los datos
      # Limito de manera general que no se repitan datos, no como con 'unique=' que es individual
      unique_together = ('name','shor_name')

    # Defino los titulos de las columnas de el admin. de Django
    def __str__(self):
      #return str(self.id) +' - '+ self.name +' - '+ self.shor_name +' - '+ str(self.anulate)
      return self.name

empleado/applications/departamento/forms.py
# Personalizacion de los Formularios en Django, el app DEPARTAMENTO
from django import forms
class NewDepartamentoForm(forms.Form):
    nombres = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

empleado/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import (ListView)
from django.views.generic.edit import FormView
from applications.personal.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm

# Create your views here.
class DepartamentoListView(ListView):
    template_name = 'departamento/lista_departamentos.html'
    #model = Departamento  # Se elimina si se usa el metod get
    # Se puede usar una variable de contexto en vez de usar en pantalla el "object_list"
    #context_object_name = 'list_dep'
    ordering = 'name'

    def get_queryset(self):
        # Codigo que filtra lista de empleados desde la pantalla
        # El 'self.request.GET.get' nos permite recoger una variable desde el HTML
        # desde un <input> y un <button>
        clave = self.request.GET.get('kword', '')
        lista = Departamento.objects.filter(
            name__icontains=clave)
        return lista
    
class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
    # Metodo que se ejecuta despues de validar y guardado los datos
    def form_valid(self, form): 
        # logica del proceso
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shortname']
        )
        depa.save()

        nombre = form.cleaned_data['nombres']
        apellido = form.cleaned_data['apellidos']
        
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        # Este me genera un error
        #return super(NewDepartamentoForm,self).form_valid(form)
        return super().form_valid(form) 

empleado/templates/departamento/lista_departamentos.html
{% extends "base.html" %}
{% block title %}
Pagina Lista Dep.
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">LISTA DE DEPARTAMENTOS</h1>
        <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" id="kword" placeholder=" Buscar departamento">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>

        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRE</th>
                        <th width="150">NOMBRE CORTO</th>
                        <th width="100">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.name }}</td>
                        <td>{{ e.shor_name}}</td>
                        <td><a class="clear button" href="{% url 'personal_app:empleados_area' e.shor_name %}">Ver empleados</a></td> 
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock content %}

empleado/templates/departamento/new_departamento.html
{% extends "base.html" %}
{% block title %}
Pagina de registro de un nuevo Empleado
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" style="text-align:center">Registrar un nuevo departamento</h1>
        {% csrf_token %}
        <form class="cell callout grid-x grid-margin-x" method="post">
        {% csrf_token %}
            <div class="medium-12 cell">
                <h3 class="cell">Datos del empleado:</h3>
                <label>Nombres:
                    {{form.nombres}}
                </label>
                <label>Apellidos:
                    {{form.apellidos}}
                </label>
            </div>
            <div class="medium-12 cell">
                <h3 class="cell">Datos del departamento:</h3>
                <label>Nombre del Departamento:
                    {{form.departamento}}
                </label>
                <label>Nombre corto del Departamento:
                    {{form.shortname}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

empleado/templates/departamento/new_departamentoOLD.html
<h1>Registrar nuevo departamento</h1>
{% csrf_token %}
<form method="POST">{% csrf_token %}
    <h3>Datos del empleado:</h3>
    <p>{{form.nombres}}</p>
    <p>{{form.apellidos}}</p>
    <h3>Datos del departamento:</h3>
    <p>{{form.departamento}}</p>
    <p>{{form.shortname}}</p>
    <button type="submit">Guardar</button>
</form>