empleado/applications/personal/urls.py
"""
"""
from django.urls import path
from . import views

app_name = 'personal_app'
urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_by_areas/<shorname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('listar_empleados/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('listar_by_kword/', views.ListEmpleadosByKword.as_view()),
    path('listar_by_habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadosDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar'),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la app departamento
    #path('depart/', include('applications.departamento.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.personal.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/personal/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
"""Modelo de la tabla de la BD Habilidades"""
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    # Defino algunas caracteristicas para el admin. de Django
    class Meta:
      verbose_name = 'Ability'  # Nombre de Columna singular
      verbose_name_plural = 'Abilities'  # Nombre en plural
      # Defino los titulos de las columnas de el admin. de Django

    def __str__(self):
      return str(self.id) + ' - ' + self.habilidad

"""Modelo de la tabla de la BD Empleado"""
class Empleado(models.Model):
    # Lista de seleccion de la columna job
    JOB_CHOICES = (
        ('0','Contractado'),
        ('1','Empleado'),
        ('2','Administrativo'),
        ('3','Ejecutivo'),
        ('4','Junta Directiva'),
        ('5','Jubilado'),
        ('6','Otros')
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('NombresCompleto', max_length=120, blank=True)
    job = models.CharField('TipoDeTrabajador', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField('Foto', upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField(blank=True, null=True)
    
    # Defino algunas caracteristicas para el admin. de Django
    class Meta:
      verbose_name = 'Employee'  # Nombre de Columna singular
      verbose_name_plural = 'My Employees'  # Nombre en plural
      ordering = ['first_name', 'last_name']  # Ordenar como se ver los datos
      # Limito de manera general que no se repitan datos, no como con 'unique=' que es individual
      unique_together = ('first_name', 'last_name')

    # Defino los titulos de las columnas de el admin. de Django
    def __str__(self):
      return str(self.id) +' - '+ self.first_name +' - '+ self.last_name +' - '+ self.job +' - '+ str(self.departamento)

empleado/applications/personal/forms.py
# Personalizacion de los Formularios en Django, el app PERSONAL
# Models de Django
from django import forms
# Models de la BD Empleado
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'image',
            'habilidades',
            )
        widgets = {
            'habilidades' : forms.CheckboxSelectMultiple()
            }

empleado/applications/personal/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ( 
    ListView, 
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
    )
# Create your views here.

# Models de la BD Empleado
from .models import Empleado
# Forms de Empleado
from .forms import EmpleadoForm

# Vista que carga la pagina de inicio
class InicioView(TemplateView):
    template_name = 'inicio.html'


# Lista todos los empleados de la empresa
class ListAllEmpleados(ListView):
    template_name = 'personal/list_all.html'
    paginate_by = 10
    ordering = 'first_name'
    #model = Empleado # Se elimina si se usa el metod get
    # Se puede usar una variable de contexto en vez de usar en pantalla el "object_list"
    #context_object_name = 'list_all'

    def get_queryset(self):
    # Codigo que filtra lista de empleados desde la pantalla
    # El 'self.request.GET.get' nos permite recoger una variable desde el HTML
    # desde un <input> y un <button>
        clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            full_name__icontains=clave)
        return lista


# Lista todos los empleados por area de la empresa
# usando una variabla en el URL
class ListByAreaEmpleados(ListView):
    template_name = 'personal/list_by_areas.html'
    paginate_by = 10
    ordering = 'first_name'

    def get_queryset(self):
        # Codigo que filtra lista de empleados desde la pantalla
        # El 'self.kwargs' nos permite recoger una variable desde el URL del HTML
        area = self.kwargs['shorname'] 
        lista = Empleado.objects.filter(
            departamento__shor_name= area)
        return lista


# Lista todos los empleados de la empresa
class ListEmpleadosAdmin(ListView):
    template_name = 'personal/list_empleados.html'
    paginate_by = 5
    ordering = 'first_name'
    model = Empleado # Se elimina si se usa el metod get
    # Se puede usar una variable de contexto en vez de usar en pantalla el "object_list"
    context_object_name = 'list_admin'


# Lista todos los empleados por nombre
# usando una variabla en un campo dentro del HTML
class ListEmpleadosByKword(ListView):
    template_name = 'personal/list_by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        # Codigo que filtra lista de empleados desde la pantalla
        # El 'self.request.GET.get' nos permite recoger una variable desde el HTML
        # desde un <input> y un <button>
        clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
                first_name=clave)
        return lista


# Lista todos los empleados por habilidades
# usando una variabla en un campo dentro del HTML
class ListHabilidadesEmpleados(ListView):
    template_name = 'personal/list_by_habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        # Codigo que filtra lista de empleados desde la pantalla
        # El 'self.request.GET.get' nos permite recoger una variable desde el HTML
        # desde un <input> y un <button>
        # El 'objects.get' nos permite buscar un emplado y luego mostrar todas sus habilidades
        clave = self.request.GET.get('kword', '')
        empleado = Empleado.objects.get(id=clave)
        return empleado.habilidades.all()


class EmpleadosDetailView(DetailView):
    template_name = 'personal/detail_empleado.html'
    model = Empleado
    # Metodo para enviar alguna otra informacion a la pantalla
    def get_context_data(self, **kwargs):
        context = super(EmpleadosDetailView,self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes' 
        return context

 
class SuccessView(TemplateView):
    template_name = 'personal/success.html'


class EmpleadoCreateView(CreateView):    
    template_name = 'personal/add.html'
    model = Empleado
    form_class =EmpleadoForm
    #fields = ['first_name', 'last_name', 'job','departamento', 'habilidades', 'image', 'hoja_vida']
    #fields = ("__all__") # Le indicas todas las columnas de la tabla
    # Cuando se usa "from_class" no es necesario utilizar el "fields" y detallar los campos
    #success_url = '.' # Le indicas la misma pagina o pantalla HTML
    # Se direcciona a otra pantalla
    #success_url = 'http://127.0.0.1:8000/listar_todos_empleados/' 
    #success_url = '/success' # No es la mejor manera de indicarlo
    success_url = reverse_lazy('personal_app:empleados_admin') # Mejor metodo de indicarlo

    # Metodo que se ejecuta despues de validar y guardado los datos
    def form_valid(self, form): 
        # logica del proceso
        # Creamos una variable que guarde los datos del formulario (una copia), los datos ya estan
        # guardados en la BD
        empleado = form.save(commit=False)  # El 'commit=False' no permite que se guarde
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        # Despues de modificar se salva en la BD
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = 'personal/update.html'
    model = Empleado
    fields = ['first_name', 'last_name', 'job',
              'departamento', 'habilidades']
    success_url = reverse_lazy('personal_app:empleados_admin')

    # Metodo que se ejecuta antes de validar y guardar los datos
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('*********POST*********')
        print(request.POST) # Se crea como un diccionario
        print('******************')
        print(request.POST['last_name']) # Se consulta como un diccionario
        return super().post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):  
    template_name = 'personal/delete.html'
    model = Empleado
    success_url = reverse_lazy('personal_app:empleados_admin')

empleado/templates/personal/add.html
{% extends "base.html" %}
{% block title %}
Pagina de registro de un nuevo Empleado
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar un nuevo Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres: 
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>foto:
                    {{form.image}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}
<!-- PARA MI ESTA ES MEJOR PARA HACER TABLAS -->
<!-- <form method="post" class="grid-x grid-padding-x">
    {% csrf_token %}
    {form.as_ul }}
    {{form.as_p }}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Agregar</button>
</form> -->

empleado/templates/personal/delete.html
{% extends "base.html" %}
{% block title %}
Eliminar empleado
{% endblock title %}
{% 
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell" aling="CENTER">Eliminar empleado</h1>
        <h3 class="cell" aling="CENTER">Nombre del empleado: {{object.full_name}} </h3>

  
        <form  class="cell" method="post">
            {% csrf_token %}
            <div class="callout alert">
                <P>Esta seguro que quiere eliminar este empleado?</P>
                <button type="submit" class="alert button">Eliminar</button>
            </div>    
        </form>
    </div>

</div>
{% endblock content %}

empleado/templates/personal/detail_empleado.html
{% extends "base.html" %}
{% block title %}
{{object.full_name}}
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="medium-6 cell card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider align-center">
            <!-- Se coloca el modelo "Empleado" pero en minuscula -->
            <!-- Se busca el dato y no el valor siempre y cuando se alla definido tipo "choices" -->
            <!-- usando el metodo get_xxx_display -->
            <p style="color:blue; font-size:30px;">{{empleado.get_job_display}}</p>
            </div>       
            {% if empleado.image %}
                <img src="{{empleado.image.url}}"><!-- Carga la imagen como una URL -->
            {% else %}
                <img src="{% static 'images/NoExiste.jpg' %}">
            {% endif %}                    
            <div class="card-section" style="text-align:center;">
                <p style="color:black; font-size:30px;">{{empleado.full_name}}</p>

                <label style="color:black; font-size:20px;"><b>Departamento:</b>
                    <!--Para ver el detalle del departamento se usa ".name o .shor_name" del modelo -->
                    <!--<input type="text" value={{empleado.departamento.shor_name}}>-->
                    <p>{{empleado.departamento.shor_name}}</p>
                </label>
                <label style="color:black; font-size:20px;"><b>Habilidades:</b>
                    <ul>      
                        {% for h in empleado.habilidades.all %}
                            <li>{{h.habilidad}}</li>  
                        {% endfor %}      
                    </ul>
                </label>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/personal/list_all.html
{% extends "base.html" %}
{% block title %}
Pagina de empleados
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">LISTA DE TODOS LOS EMPLEADOS</h1>       
        <form method="get" class="cell grid-x grid-margin-x">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" id="kword" placeholder=" Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRE</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="100">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name}}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="clear button" href="{% url 'personal_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    
                    {% if  page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}                    
                        {% if pagina == page_obj.number  %}
                        <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                        {% else %}
                        <li><a href="?page={{ pagina }}" aria-label="Page">{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
                

        </div>
    </div>  
</div>
{% endblock content %}

empleado/templates/personal/list_by_areas.html
{% extends "base.html" %}
{% block title %}
Pagina de empleados
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">LISTA DE TODOS LOS EMPLEADOS POR AREA</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRE</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="100">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name}}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="clear button" href="{% url 'personal_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="cell">

            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                    {% if pagina == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{ pagina }}" aria-label="Page">{{ pagina }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/personal/list_by_habilidades.html
<h1>Lista de empleados por habilidades</h1>
{% csrf_token %}
<!--El token es por seguridad para que nadie mas tenga acceso-->
<form method="get">
    <input type="text" id="kword" name="kword" placeholder="ingrese id aqui:">
    <button type="submit">Buscar</button>
</form>
<br>
<ul>
    {% for h in object_list %}
    <li>{{h}}</li>
    {%endfor%}
</ul>

empleado/templates/personal/list_by_kword.html
<h1>LISTADO DE EMPLEADO POR BUSQUEDA EN EL HTML</h1>
<h3>USANDO UNA PALABRA CLAVE DESDE UN CAMPO</h3>
<br>
{% csrf_token %} <!--El token es por seguridad para que nadie mas tenga acceso-->
<form method="get">
    <input type="text" id="kword" name="kword" placeholder="ingrese area aqui:">
    <button type="submit">Buscar</button>
</form>
<br>
<br>
<ul>
    {% for e in object_list %}
    <li>{{ e.first_name }} - {{ e.last_name }}</li>
    {%endfor%}
</ul>

empleado/templates/personal/list_empleados.html
{% extends "base.html" %}
{% block title %}
Pagina de empleados
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">LISTA DE TODOS LOS EMPLEADOS - ADMINSTRACION</h1>       
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRE</th>
                        <th width="150">APELLIDO</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in list_admin %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name}}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="clear button" href="{% url 'personal_app:empleado_detail' e.id %}">Ver</a>
                            &nbsp;
                            <a class="clear button" href="{% url 'personal_app:modificar' e.id %}"> Editar</a>
                            &nbsp;
                            <a class="clear button" href="{% url 'personal_app:eliminar' e.id %}"> Eliminar</a>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    
                    {% if  page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}                    
                        {% if pagina == page_obj.number  %}
                        <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                        {% else %}
                        <li><a href="?page={{ pagina }}" aria-label="Page">{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
                

        </div>
    </div>  
</div>
{% endblock content %}

empleado/templates/personal/success.html
<h1>Felicitaciones, se guardo o elimino correctamente el empleado</h1>

empleado/templates/personal/update.html
{% extends "base.html" %}
{% block title %}
Pagina de empleados
{% endblock title %}
{% block content %}
{% include 'includes/header.html'%}
{% load static %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">MODIFICAR DATOS DEL EMPLEADO</h1>
        <div class="cell" align="CENTER">
            <form method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <button type="submit" class="submit success button">Modificar</button>
            </form>
        </div>    
    </div>        
</div>
{% endblock content %}